# frozen_string_literal: true

require_relative '../../lib/version'

namespace :ktlint do
  desc 'Download and install ktlint tool'
  task :install do
    next if ENV['DANGER_SKIP_KTLINT_INSTALL'] == 'YES'

    REPO = 'https://github.com/pinterest/ktlint'
    VERSION = ENV['KTLINT_VERSION'] || DangerKtlint::KTLINT_VERSION
    ASSET = 'ktlint'
    URL = "#{REPO}/releases/download/#{VERSION}/#{ASSET}"
    DESTINATION = File.expand_path(File.join(File.dirname(__FILE__), 'bin'))

    puts "Downloading ktlint@#{VERSION}"
    sh [
      "mkdir -p '#{DESTINATION}'",
      "curl -s -L #{URL} -o #{ASSET}",
      "unzip -q #{ASSET} -d '#{DESTINATION}'",
      "rm #{ASSET}"
    ].join(' && ')
  end
end

task default: 'ktlint:install'
